import importlib

from .audit import ObjectiveWeights, audit_dialogue, audit_dialogue_multi, replay_event_log
from .benchmarks import (
    BenchmarkCase,
    BenchmarkExpectation,
    BenchmarkSuite,
    GateExpectation,
    PairExpectation,
    benchmark_case_from_dict,
    benchmark_expectation_from_dict,
    benchmark_suite_from_dict,
    dialogue_event_from_dict,
    load_benchmark_suite,
    pair_expectation_from_dict,
)
from .control import GateThresholds, control_observation_to_telemetry, estimate_control_axes, estimate_control_axes_legacy
from .decoder import DecoderConfig, decode_bcg_profile, decode_bcg_to_geom
from .models import (
    AlternativeProgram,
    AuditResult,
    BCGVector,
    ControlObservation,
    ControlState,
    CrossSystemConflict,
    DialogueEvent,
    GeomBlock,
    MoralSystemProfile,
    MoveRecord,
    MultiAuditResult,
    OmegaState,
    Principle,
    SpectralState,
    SystemAuditResult,
    ViolationRecord,
)
from .mcd import load_snapshots, persist_snapshots, replay_snapshots
from .principles import default_principles
from .profiles import (
    BUILTIN_PROFILE_DIR,
    default_moral_system_profile,
    load_builtin_moral_system_profiles,
    load_moral_system_profile,
    load_moral_system_profiles,
    moral_system_profile_from_dict,
    principle_from_dict,
)
from .scoring import (
    BenchmarkCaseScore,
    BenchmarkSuiteScore,
    ExtraLabelReport,
    ExtraLabelReportRow,
    OMB24RubricV2,
    OMB24RubricV3,
    PairInvarianceScore,
    SystemReferenceScore,
    ViolationHierarchy,
    expected_subset_recall,
    format_extra_label_report,
    over_trigger_penalty,
    score_benchmark_case,
    score_benchmark_suite,
)
from .runtime import (
    VLLMColdPathResult,
    VLLMHotPathSample,
    VLLMRollbackTrace,
    distribution_entropy,
    event_with_vllm_runtime,
    fisher_rao_distance,
    jensen_shannon_divergence,
    runtime_meta_from_event_meta,
    runtime_meta_from_vllm_payloads,
    telemetry_from_vllm_payloads,
)
from .runtime_smoke import (
    RELEASE_ID,
    RuntimeSmokeCase,
    RuntimeSmokeCaseResult,
    RuntimeSmokeSuiteResult,
    build_runtime_smoke_cases,
    run_runtime_smoke_suite,
)
from .truthfulqa_mini import (
    TRUTHFULQA_DATASET_URL,
    TRUTHFULQA_PAPER_URL,
    TruthfulQASelection,
    build_truthfulqa_mini_suite,
    write_truthfulqa_outputs,
)
from .ablation import (
    ABLATION_MODES,
    SixAxisAblationMode,
    SixAxisAblationModeResult,
    SixAxisAblationSuiteReport,
    format_six_axis_ablation,
    run_six_axis_ablation,
    write_six_axis_ablation,
)
from .bbq_mini import (
    BBQ_DATASET_URL,
    BBQ_GITHUB_URL,
    BBQ_PAPER_URL,
    BBQSelection,
    build_bbq_mini_suite,
    write_bbq_outputs,
)
from .formula import (
    FORMULA_REFERENCE,
    FormulaPipelineResult,
    demo_pipeline,
    get_formula_reference,
    run_ethics_pipeline,
)
from .text_control import (
    ClaimAnalysis,
    TextControlResult,
    analyze_claims,
    estimate_control_from_text,
)
from .text_ethics import (
    QuickEthicsReport,
    TextAnalysis,
    analyze_text,
    analysis_to_bcg_profile,
    batch_audit_texts,
    quick_ethics_audit,
)
from .spectral import ScalarizerConfig, scalarize, spectral_from_blocks
from .six_axes import (
    AXIS_ORDER,
    AxisAssessment,
    StabilityCalibrationPoint,
    SixAxisAssessment,
    SixAxisSnapshot,
    SixAxisTelemetry,
    SixAxisThresholds,
    SixAxisWeights,
    TauCalibrationPoint,
    beta_c_upper_bound,
    beta_s_value,
    build_layer_weights,
    calibrate_stability_gamma,
    causal_mass,
    consensus_score_from_clusters,
    estimate_tau_hybrid_v1_5,
    estimate_tau_proxy_v2,
    evaluate_six_axes,
    legal_progress,
    normalized_entropy,
    relative_state_variation,
    rollback_rate,
    solve_tau_alpha_star,
    tau_alpha_error_bound,
    tau_nli_tolerance_threshold,
    weighted_attention_leak,
)

__all__ = [
    "AlternativeProgram",
    "AuditResult",
    "BCGVector",
    "BenchmarkCase",
    "BenchmarkCaseScore",
    "BenchmarkExpectation",
    "BenchmarkSuite",
    "BenchmarkSuiteScore",
    "ComparativeBaselineReport",
    "ComparativeBaselineSuiteReport",
    "BaselineModeResult",
    "ComparativeCaseResult",
    "ComparativeSuiteReport",
    "ExtraLabelReport",
    "ExtraLabelReportRow",
    "AXIS_ORDER",
    "AxisAssessment",
    "ControlObservation",
    "ControlState",
    "CrossSystemConflict",
    "DecoderConfig",
    "DialogueEvent",
    "GateExpectation",
    "GateThresholds",
    "GeomBlock",
    "MoralSystemProfile",
    "MoveRecord",
    "MultiAuditResult",
    "ObjectiveWeights",
    "OMB24RubricV2",
    "OMB24RubricV3",
    "OmegaState",
    "PairExpectation",
    "PairInvarianceScore",
    "BBQ_DATASET_URL",
    "BBQ_GITHUB_URL",
    "BBQ_PAPER_URL",
    "BBQSelection",
    "PROFILE_IDS",
    "Principle",
    "ProfileJudgment",
    "RELEASE_ID",
    "TRUTHFULQA_DATASET_URL",
    "TRUTHFULQA_PAPER_URL",
    "TruthfulQASelection",
    "RuntimeSmokeCase",
    "RuntimeSmokeCaseResult",
    "RuntimeSmokeSuiteResult",
    "ScalarizerConfig",
    "SixAxisAssessment",
    "SixAxisAblationMode",
    "SixAxisAblationModeResult",
    "SixAxisAblationSuiteReport",
    "StabilityCalibrationPoint",
    "SixAxisSnapshot",
    "SixAxisTelemetry",
    "SixAxisThresholds",
    "SixAxisWeights",
    "SpectralState",
    "SystemReferenceScore",
    "SystemAuditResult",
    "ViolationHierarchy",
    "ViolationRecord",
    "VLLMColdPathResult",
    "VLLMHotPathSample",
    "VLLMRollbackTrace",
    "BUILTIN_PROFILE_DIR",
    "audit_dialogue",
    "audit_dialogue_multi",
    "beta_c_upper_bound",
    "beta_s_value",
    "benchmark_case_from_dict",
    "benchmark_expectation_from_dict",
    "benchmark_suite_from_dict",
    "build_bbq_mini_suite",
    "build_comparative_baseline_report",
    "build_cross_cultural_suite",
    "build_cross_profile_suite",
    "build_truthfulqa_mini_suite",
    "build_multi_agent_suite",
    "build_layer_weights",
    "build_runtime_smoke_cases",
    "calibrate_stability_gamma",
    "causal_mass",
    "consensus_score_from_clusters",
    "decode_bcg_profile",
    "decode_bcg_to_geom",
    "default_moral_system_profile",
    "default_principles",
    "dialogue_event_from_dict",
    "distribution_entropy",
    "control_observation_to_telemetry",
    "expected_subset_recall",
    "event_with_vllm_runtime",
    "estimate_control_axes",
    "estimate_control_axes_legacy",
    "estimate_tau_hybrid_v1_5",
    "estimate_tau_proxy_v2",
    "evaluate_six_axes",
    "format_comparative_baseline_report",
    "format_extra_label_report",
    "format_comparative_report",
    "format_six_axis_ablation",
    "fisher_rao_distance",
    "jensen_shannon_divergence",
    "legal_progress",
    "load_snapshots",
    "load_builtin_moral_system_profiles",
    "load_benchmark_suite",
    "load_moral_system_profile",
    "load_moral_system_profiles",
    "moral_system_profile_from_dict",
    "normalized_entropy",
    "over_trigger_penalty",
    "pair_expectation_from_dict",
    "persist_snapshots",
    "principle_from_dict",
    "relative_state_variation",
    "replay_event_log",
    "replay_snapshots",
    "rollback_rate",
    "run_comparative_suite",
    "run_six_axis_ablation",
    "run_runtime_smoke_suite",
    "runtime_meta_from_event_meta",
    "runtime_meta_from_vllm_payloads",
    "scalarize",
    "score_benchmark_case",
    "score_benchmark_suite",
    "solve_tau_alpha_star",
    "spectral_from_blocks",
    "TauCalibrationPoint",
    "tau_alpha_error_bound",
    "tau_nli_tolerance_threshold",
    "telemetry_from_vllm_payloads",
    "weighted_attention_leak",
    "write_comparative_baseline_outputs",
    "write_comparative_outputs",
    "write_six_axis_ablation",
    "write_bbq_outputs",
    "write_truthfulqa_outputs",
    "ABLATION_MODES",
    "CORE_CLAIM",
    # formula pipeline
    "FORMULA_REFERENCE",
    "FormulaPipelineResult",
    "demo_pipeline",
    "get_formula_reference",
    "run_ethics_pipeline",
    # text control estimation
    "ClaimAnalysis",
    "TextControlResult",
    "analyze_claims",
    "estimate_control_from_text",
    # text-to-ethics
    "QuickEthicsReport",
    "TextAnalysis",
    "analyze_text",
    "analysis_to_bcg_profile",
    "batch_audit_texts",
    "quick_ethics_audit",
]

_LAZY_COMPARATIVE_EXPORTS = {
    "comparative_audit",
    "comparative_baseline",
    "ComparativeBaselineReport",
    "ComparativeBaselineSuiteReport",
    "BaselineModeResult",
    "PROFILE_IDS",
    "CORE_CLAIM",
    "ComparativeCaseResult",
    "ComparativeSuiteReport",
    "ProfileJudgment",
    "build_comparative_baseline_report",
    "build_cross_cultural_suite",
    "build_cross_profile_suite",
    "build_multi_agent_suite",
    "format_comparative_baseline_report",
    "format_comparative_report",
    "write_comparative_baseline_outputs",
    "run_comparative_suite",
    "write_comparative_outputs",
}


def __getattr__(name: str):
    if name in _LAZY_COMPARATIVE_EXPORTS:
        module_name = ".comparative_baseline" if name in {
            "comparative_baseline",
            "ComparativeBaselineReport",
            "ComparativeBaselineSuiteReport",
            "BaselineModeResult",
            "CORE_CLAIM",
            "build_comparative_baseline_report",
            "format_comparative_baseline_report",
            "write_comparative_baseline_outputs",
        } else ".comparative_audit"
        module = importlib.import_module(module_name, __name__)
        if name in {"comparative_audit", "comparative_baseline"}:
            value = module
        else:
            value = getattr(module, name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
